name: Publish | oidc-provider
run-name: Publish | oidc-provider | ${{ inputs.environment || github.ref_name }}

on:
  push:
    branches:
      - production
      - staging
      - dev
      - canary
    paths:
      - '.github/workflows/publish-oidc-provider.yml'
      - 'package-lock.json'
      - 'eaas-shared/**'
      - 'shared/**'
      - 'oidc-provider/**'
      - '!oidc-provider/INSTRUCTIONS.md'
      - '!oidc-provider/README.md'
      - '!oidc-provider/.dev.vars.example'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to:'
        required: true
        default: 'canary'
        type: environment

env:
  WORKER_NAME: oidc-provider

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || github.ref_name }}
      url: https://${{ (inputs.environment || vars.ENVIRONMENT) != 'production' && format('{0}.', (inputs.environment || vars.ENVIRONMENT)) || '' }}provider.oidc.cipher.chainfuse.ai
      # url: https://${{ (inputs.environment || vars.ENVIRONMENT) != 'production' && format('{0}.', (inputs.environment || vars.ENVIRONMENT)) || '' }}provider.oidc.cipher.autosec.network
    steps:
      - uses: step-security/harden-runner@v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v4.0.0
        with:
          submodules: true
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json
      - name: Install root deps
        run: npm ci
      - name: Install submodule deps
        run: npm ci
        working-directory: eaas-shared
      - name: Install deps
        run: npm ci
        working-directory: ${{ env.WORKER_NAME }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_WRANGLER_API_TOKEN }}
          accountId: ${{ secrets.CF_WRANGLER_ACCOUNT_ID }}
          environment: ${{ vars.ENVIRONMENT != 'canary' && vars.ENVIRONMENT || '' }}
          workingDirectory: ${{ env.WORKER_NAME }}
          vars: |
            GIT_HASH
        env:
          GIT_HASH: ${{ github.sha }}
